import Head from 'next/head';

export default function LandingPageSEO() {
  // Website URL
  const siteUrl = 'https://storyincolor.com';
  
  // Define structured data for rich search results
  const webAppSchema = {
    "@context": "https://schema.org",
    "@type": "WebApplication",
    "name": "StoryInColor",
    "url": siteUrl,
    "applicationCategory": "MultimediaApplication",
    "description": "Turn your photos into beautiful custom coloring pages instantly with AI. Create personalized coloring books from vacation photos, family pictures, and pet portraits.",
    "offers": {
      "@type": "Offer",
      "price": "0.45",
      "priceCurrency": "USD",
      "description": "Pay per coloring page generation with credits"
    },
    "screenshot": `${siteUrl}/images/SHARING.webp`,
    "featureList": "AI photo to coloring page conversion, instant PDF download, multiple art styles, easy customization",
    "operatingSystem": "Any modern web browser"
  };
  
  const faqSchema = {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    "mainEntity": [
      {
        "@type": "Question",
        "name": "What kind of photos can I use?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": "You can use a wide variety of photos, including vacation pictures, family portraits, pet photos, and even landscape shots. High-quality images with good lighting and clear subjects work best for optimal conversion to coloring pages."
        }
      },
      {
        "@type": "Question",
        "name": "How long does it take to get my coloring pages?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": "Your custom coloring pages are generated by our AI almost instantly. After uploading your photos and making any desired adjustments, you can download the PDF immediately."
        }
      },
      {
        "@type": "Question",
        "name": "Can I use these pages for commercial purposes?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": "The coloring pages you create are for personal use only. They are a great activity for families, a unique gift, or a relaxing hobby. Commercial use or redistribution is not permitted."
        }
      }
    ]
  };

  const howToSchema = {
    "@context": "https://schema.org",
    "@type": "HowTo",
    "name": "How to Create Custom Coloring Pages",
    "description": "Follow these three simple steps to transform your photos into personalized coloring pages.",
    "step": [
      {
        "@type": "HowToStep",
        "name": "Step 1: Upload Photos",
        "text": "Upload your vacation photos, family pictures, or any special memories you want to transform.",
        "url": `${siteUrl}#how-it-works`,
        "image": `${siteUrl}/images/how-to-upload.webp` 
      },
      {
        "@type": "HowToStep",
        "name": "Step 2: Preview & Customize",
        "text": "Our AI converts your photos into coloring pages. Preview and make adjustments to get the best results.",
        "url": `${siteUrl}#how-it-works`,
        "image": `${siteUrl}/images/how-to-customize.webp`
      },
      {
        "@type": "HowToStep",
        "name": "Step 3: Download Your Pages",
        "text": "Download your personalized coloring pages instantly and print them at home for immediate enjoyment.",
        "url": `${siteUrl}#how-it-works`,
        "image": `${siteUrl}/images/how-to-download.webp`
      }
    ]
  };

  return (
    <Head>
      <title>StoryInColor - Turn Photos Into Custom Coloring Pages with AI</title>
      <meta name="description" content="Instantly convert your photos into beautiful custom coloring pages with our AI-powered tool. Perfect for family pictures, pet portraits, and vacation memories. Download and print your personalized coloring book today!" />
      <meta name="keywords" content="custom coloring pages, photo to coloring page, AI coloring pages, personalized coloring book, printable coloring pages, family coloring book, pet coloring pages, create coloring book from photos" />
      
      <meta property="og:type" content="website" />
      <meta property="og:url" content={siteUrl} />
      <meta property="og:title" content="StoryInColor - Turn Your Photos Into Beautiful Custom Coloring Pages" />
      <meta property="og:description" content="Create beautiful personalized coloring pages from your favorite photos. Our AI makes it easy to turn pictures of family, pets, and vacations into fun, printable coloring sheets." />
      <meta property="og:image" content={`${siteUrl}/images/SHARING.webp`} />
      
      <meta property="twitter:card" content="summary_large_image" />
      <meta property="twitter:url" content={siteUrl} />
      <meta property="twitter:title" content="StoryInColor - AI-Powered Custom Coloring Pages" />
      <meta property="twitter:description" content="Turn your photos into beautiful coloring pages instantly with AI. Create personalized coloring books from vacation photos, family pictures, and pet portraits." />
      <meta property="twitter:image" content={`${siteUrl}/images/SHARING.webp`} />
      
      <link rel="canonical" href={siteUrl} />
      
      <script 
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(webAppSchema) }}
        key="webapp-schema"
      />
      <script 
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }}
        key="faq-schema"
      />
       <script 
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(howToSchema) }}
        key="howto-schema"
      />
    </Head>
  );
} 